config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end
  
  root to: "home#index"

  get 'home/index'
  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'
  
  resource :contacts, only: [:new, :create], path_names: { :new => '' }
  resources :articles do 
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true
  has_many :comments

  def subject 
    title
  end

  def last_comment  
    comments.last
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    # devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 
  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

  #показываем список
  def index 
    @articles = Article.all
  end

  # по URL переходим к определенной статье
  #views/articles/show.html.erb
  def show 
    @article = Article.find(params[:id])
  end

  def new
  end

  def create 
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article #при создание новой статьи автоматический идет редирект на show
    else
      render action: 'new'
    end
  end

  def edit 
    @article = Article.find(params[:id])
  end

  def update 
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article #при создание новой статьи автоматический идет редирект на show
    else
      render action: 'edit'
    end
  end

  def destroy 
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params 
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :authenticate_user!, :only => [:new, :create]

  def create 
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

  private

  def comment_params 
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new 
  end

  def create 
    @contact = Contact.new(contact_params)
    if @contact.valid? 
      @contact.save
    else
      render action: 'new'
    end
  end

  private

  def contact_params 
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms 
  end

  def about 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%# меняем action на article_path(@article) см код в браузере %> 
<%# method: :put для того чтобы можно было редактировать, по умолчанию было post  %> 
<%= form_for :article, url: article_path(@article), method: :put, data: {turbo:false} do |f| %>
  <p>
    <%= f.label :title %></br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %></br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit%>
  </p>
<% end %>

app/views/articles/index.html.erb
<% @articles.each do |article|%>

  <h3>
    <%= article.title %>
  </h3>
  
  <p>
    <%= article.text %>
  </p>
 
  <p>
    Created at <%= article.created_at.strftime("%H:%M %d %b %Y")%>
  </p>

  <p>
    <%= link_to 'Show', article_path(article) %> |
    <%= link_to 'Edit', edit_article_path(article) %> |
    <%= link_to 'Destroy', article_path(article), data: {'turbo-method': :delete, 'turbo-confirm': "Are you shure?"} %>
  </p>
 <hr />
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= form_for :article, url: articles_path, data: {turbo:false} do |f| %>
  <p>
    <%= f.label :title %></br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %></br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit%>
  </p>
<% end %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>

<p>
  <%= @article.text %>
</p>
<hr />
<h3>Comments</h3>

<% @article.comments.each do |comment|%>

  <p>
    <i> <%= comment.author %> </i> said: </br>  
    <%= comment.body %>
  </p>
 
  <p>
    <%= comment.created_at.strftime("%H:%M:%S %d %b %Y")%>
  </p>
  <hr />
<% end %>

<h3>Add comment</h3>

<%# получаем такой URL для комментария /articles/8/comments%>

<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :author %></br>
    <%= f.text_field :author %>
  </p>

  <p>
    <%= f.label :body %></br>
    <%= f.text_area :body %>
  </p>

  <p> 
    <%= f.submit%>
  </p>
<% end %>

<p><%= link_to "Back", articles_path %></p>


app/views/contacts/create.html.erb
<p>Thanks!</p>

app/views/contacts/new.html.erb
<h2><%= t("contacts.contact") %></h2>

<%= form_for :contact, url: contacts_path, data: {turbo:false} do |f| %>
  <% if @contact && @contact.errors.any? %>
  <p>
    <ul>
    <% @contact.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>  
  </p>
  <% end %>

  <p>
    <%= f.label :email %></br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :message %></br>
    <%= f.text_area :message %>
  </p>

  <p>
    <%= f.submit 'Send message'%>
  </p>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogPost</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <% if user_signed_in? %>

  Hello, <%= current_user.username%> | <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>

  <% else %>

  <%= link_to 'Sign In', new_user_session_path %>
  
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h2>
<p> 
  We are ...
</p>

app/views/pages/terms.html.erb
<h1>Terms Of Service</h1>
<p>
Something text ...
</p>